<a href="https://colab.research.google.com/github/aditya-pandey-ai/Projects/blob/master/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this file I trained a model using the Simple MNIST dataset
which is used to classify images



In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01862293, -0.4593196 ,  0.07501903, -0.64734584, -1.655127  ,
         0.04018699,  0.5709466 , -0.73838377, -0.03141998, -0.56438553]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.12319901, 0.07639051, 0.1303466 , 0.06329663, 0.02310504,
        0.12588453, 0.2140318 , 0.05778876, 0.11718549, 0.06877171]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.0723903

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2967 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1450 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1086 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0888 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0761 - accuracy: 0.9763


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0739 - accuracy: 0.9778 - 562ms/epoch - 2ms/step


[0.0739186555147171, 0.9778000116348267]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.02513864e-08, 9.09260223e-10, 2.15615415e-07, 1.05486815e-05,
        3.66450712e-13, 4.48846365e-08, 2.62521152e-13, 9.99988675e-01,
        1.42760594e-08, 5.31872502e-07],
       [1.20091741e-08, 9.27212932e-06, 9.99982476e-01, 4.60231013e-06,
        5.61901498e-14, 2.54630481e-06, 5.45214967e-08, 9.14163019e-15,
        1.05307390e-06, 1.77075607e-12],
       [3.51602090e-08, 9.99861002e-01, 6.76973059e-06, 7.70202575e-07,
        9.55540327e-06, 1.05322715e-06, 5.44813304e-07, 9.30918395e-05,
        2.71075005e-05, 4.63526462e-08],
       [9.99879956e-01, 2.06407691e-09, 1.31548404e-05, 9.17676068e-09,
        2.70361209e-08, 2.03922639e-07, 9.68305685e-05, 8.56219049e-06,
        1.86650393e-08, 1.17173147e-06],
       [4.30816999e-06, 2.80215628e-09, 1.35112978e-05, 4.20375585e-07,
        9.97120500e-01, 8.21646537e-08, 2.02548813e-06, 2.12751067e-04,
        1.36246126e-06, 2.64505460e-03]], dtype=float32)>